server:
  port: ${PORT:8080}
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://eureka-service:8761/eureka
    instance:
      hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: catalog-service
          uri: lb://catalog-service
          predicates:
            - Path=/catalog/**
        - id: movies-service
          uri: lb://movies-service
          predicates:
            - Path=/movies/**
        - id: series-service
          uri: lb://series-service
          predicates:
            - Path=/series/**

management:
  endpoints:
    web:
      exposure:
        include: health, info, gateway

info:
  app:
    name: gateway-service
    description: Gateway Service
    version: 1.0.0