#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka

#Configuraciones para ACTUATOR
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: serviceregistry, health, info
