#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka

spring:
  zipkin:
    enabled: true
    baseUrl: http://zipkin:9411

#Configuraciones para ACTUATOR
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: serviceregistry, health, info
