server:
  port: ${PORT:8084}
  #antes ${PORT:8084} - MULTUPLE-INSTANCES -> SERVER_PORT:0 para que me de un puerto cualquiera que no esté en uso
  #port: ${PORT:${SERVER_PORT:0}}

spring:
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: catalogdb
      port: 27017
      host: mongodb

#eureka:
#  client:
    # True para que se registre en el servidor de EUREKA
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      default-zone: http://eureka-server:8761/eureka
#    instance:
#      instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}

#Configuración del circuit breaker
resilience4j:
  circuitbreaker:
    instances:
      moviesCB:
        registerHealthIndicator: true
        slidingWindowSize: 3
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 3
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        allowHealthIndicatorToFail: false
      seriesCB:
        registerHealthIndicator: true
        slidingWindowSize: 3
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 3
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        allowHealthIndicatorToFail: false
      catalogCB:
        registerHealthIndicator: true
        slidingWindowSize: 3
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 3
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        allowHealthIndicatorToFail: false

#Configuración del mecanismo de reintentos
  retry:
    instances:
      catalogCB:
        maxAttemps: 3
        waitDuration: 1000
        retryExceptions[0]: feign.FeignException$InternalServerError

#Actuator
management:
  endpoints:
    web:
      exposure:
        include: health, info, circuitbreakers, circuitbreakerevents
info:
  app:
    name: ${spring.application.name}
    description: Catalog Service
    version: 1.0.0
