server:
  port: ${PORT:8084}
  #antes ${PORT:8084} - MULTUPLE-INSTANCES -> SERVER_PORT:0 para que me de un puerto cualquiera que no esté en uso
  #port: ${PORT:${SERVER_PORT:0}}

spring:
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: catalogdb
      port: 27017
      host: mongodb


#Configuración del circuit breaker
resilience4j:
  circuitbreaker:
    instances:
      moviesCB:
        registerHealthIndicator: true
        slidingWindowSize: 3                      #Cantidad de eventos a esperar
        permittedNumberOfCallsInHalfOpenState: 2  #Cantidad de intentos de peticiones en estado semiabierto
        slidingWindowType: COUNT_BASED            #Analiza por cantidad de eventos
        minimumNumberOfCalls: 3                   #Cantidad mínima de llamadas
        waitDurationInOpenState: 5s               #Tiempo de espera con circuit breaker en estado abierto
        failureRateThreshold: 50                  #Límite de fallas permitidas - 50%
        eventConsumerBufferSize: 10
        allowHealthIndicatorToFail: false
      seriesCB:
        registerHealthIndicator: true
        slidingWindowSize: 3
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 3
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        allowHealthIndicatorToFail: false
      catalogCB:
        registerHealthIndicator: true
        slidingWindowSize: 3
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 3
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        allowHealthIndicatorToFail: false

#Configuración del mecanismo de reintentos
  retry:
    instances:
      catalogCB:
        maxAttemps: 3
        waitDuration: 1000
        retryExceptions[0]: feign.FeignException$InternalServerError

#Actuator
management:
  endpoints:
    web:
      exposure:
        include: health, info, circuitbreakers, circuitbreakerevents
  health:
    #Para habilitar el endpoint /circuitbreakers
    circuitbreakers:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    description: Catalog Service
    version: 1.0.0