server:
  #antes ${PORT:8082} - MULTUPLE-INSTANCES -> SERVER_PORT:0 para que me de un puerto cualquiera que no esté en uso
  port: ${PORT:${SERVER_PORT:0}}
eureka:
  client:
    # True para que se registre en el servidor de EUREKA
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://eureka-server:8761/eureka
    instance:
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://mysql:3306/moviesdb
    username: user
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver

info:
  app:
    name: ${spring.application.name}
    description: Movie Service
    version: 1.0.0
