server:
  port: ${PORT:8082}
  #MULTIPLE-INSTANCES -> SERVER_PORT:0 para que me de un puerto cualquiera que no esté en uso
  #port: ${PORT:${SERVER_PORT:0}}

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://mysql:3306/moviesdb
    username: user
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver

info:
  app:
    name: ${spring.application.name}
    description: Movie Service
    version: 1.0.0