server:
  port: ${PORT:8083}
  #antes ${PORT:8083} - MULTUPLE-INSTANCES -> SERVER_PORT:0 para que me de un puerto cualquiera que no esté en uso
  #port: ${PORT:${SERVER_PORT:0}}

spring:
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: seriesdb
      port: 27017
      host: mongodb

  info:
    app:
      name: ${spring.application.name}
      description: Series Service
      version: 1.0.0
