server:
  port: ${PORT:8083}
  #antes ${PORT:8083} - MULTUPLE-INSTANCES -> SERVER_PORT:0 para que me de un puerto cualquiera que no esté en uso
  #port: ${PORT:${SERVER_PORT:0}}

spring:
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: seriesdb
      port: 27017
      host: mongodb

eureka:
  client:
    # True para que se registre en el servidor de EUREKA
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://eureka-server:8761/eureka
    instance:
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

  info:
    app:
      name: ${spring.application.name}
      description: Series Service
      version: 1.0.0
