server:
  port: ${PORT:8888}
spring:
  cloud:
    config:
      server:
        git:
          default-label: rabbitMQ
          uri: https://github.com/tanaivcaci/dh-final-backEnd1
          search-paths: config-data
  application:
    name: server-config
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
