server:
  port: ${PORT:8888}
spring:
  cloud:
    config:
      server:
        git:
          default-label: gateway
          uri: https://github.com/tanaivcaci/dh-final-backEnd1
          search-paths: config-data
  application:
    name: server-config